kind: source
spec:
  name: gcp
  path: cloudquery/gcp
  version: "v8.4.2" # latest version of gcp plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v3.0.2" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
