kind: source
spec:
  name: gcp
  path: cloudquery/gcp
  version: "v2.0.3" # latest version of gcp plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v1.3.5" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
